### ISSUE TITLE
EAP Connection Configuration GUI double use "Client Credentials" Category

### ISSUE THREAD

**Issue by dhpark21** [Amebis/GEANTLink#20]
EAP Connection Configuration GUI double used "Client Credentials" Category

I think 
UP : Client Credentials is used profile...
Below : Client Cerdentials is used TLS CA..

It(Below) may be Change name

Thanks

**Comment by rozmansi** [comment]
Yes, I know. That is because the same `wxPanel` is reused for all kind of credential selections.
