### ISSUE TITLE
TTLS "User Certificate" not necessary

### ISSUE THREAD

**Issue by dhpark21** [Amebis/GEANTLink#23]
Hi.
As you know, below red chapter is not necessary at TTLS
It is used at EAP-TLS, but not support yet.
So, I think this chapter will hidden until support EAP-TLS
Chack it 
Thanks

![cert](https://cloud.githubusercontent.com/assets/12795655/19144987/b8481372-8be7-11e6-8324-5c40a4445339.PNG)

**Comment by rozmansi** [comment]
True, EAP-TTLS identifies user in inner authentication stage later. Thus it makes little sense identifying user with client certificate early in the TLS authentication stage. Therefore, most real-world configurations do not require a client certificate.

However, EAP-TTLS RFC is crystal clear that TLS client certificates _can_ be used too:

[RFC 5281, 5.2. Security Relationships](https://tools.ietf.org/html/rfc5281#section-5.2):

> The client and TTLS server may have a one-way security relationship
>    based on the TTLS server's possession of a private key guaranteed by
>    a CA certificate which the user trusts, **or may have a mutual security
>    relationship based on certificates for both parties**.

[RFC 5281, 5.3. Messaging](https://tools.ietf.org/html/rfc5281#section-5.3):

> During the first phase of the negotiation, the TLS handshake protocol
>    is used to authenticate the TTLS server to the client and,
>    **optionally, to authenticate the client to the TTLS server,** based on
>    public/private key certificates...

... and so on.

Therefore, this option stays.

Nevertheless:
- It was sorted at the very bottom of the configuration dialog for the very reason, probably nobody would use it.
- It defaults to typical non-client certificate scenario when you configure a new connection and identity provider.
