### ISSUE TITLE
EAP Connection Configuration stopped working after Switch to Visual Studio 2017

### ISSUE THREAD

**Issue by gigafact** [Amebis/GEANTLink#25]
On Windows 7 SP1 clean install (without any additional net framework installed) when I try to run [Settings](https://img1.picload.org/image/dcgraiol/capture.png) (EAP Connection Configuration) in the Authentication tab on Local Area Connection Properties nothing happens. What do I need to install to be able to run newer versions than 1.2c on windows 7 systems. I am guessing I need to install net framework 4+ or something similar but I just wanted to ask first before trying different framework versions.
Version 1.2c and below run without any problems.
Thanks for developing an amazing application.

**Comment by rozmansi** [comment]
Thank you for reporting this. I shall look into it.
