### ISSUE TITLE
Credentials still missing

### ISSUE THREAD

**Issue by ikreb7** [Amebis/GEANTLink#27]
Hallo Simon,
I have the problem, that GÉANTLink starts itself several times to ask for the credentials. Do you have any idea how to fix this?

I tested it under Windows 10 build 1803 and 1809. But it works earlier. I will test it soon with 1904

**Comment by rozmansi** [comment]
Are you using EAP-TTLS with MSCHAPv2 for authentication? I received a report of similar issue where it keeps prompting for credentials.

May you try an older version of GÉANTLink please and report back?

I am planning to set up a test lab in August and will take a look at this too.

**Comment by ikreb7** [comment]
I use EAP-TTLS.

>May you try an older version of GÉANTLink please and report back?

I will do this. I tested already GÉANTLink 1.1h and 1.2f.  

>I am planning to set up a test lab in August and will take a look at this too.

Sounds good.

**Comment by rozmansi** [comment]
I am able to reproduce this bug using EAP-TTLS+EAP-MSCHAPv2. There are two credential prompts when connecting (provided you don't have credentials saved). The second prompt may be canceled and the connection still succeeds.

**Comment by ikreb7** [comment]
Yes, but this distract our users and call our it support very often. So it would be very nice, if only one window for the credentials appears.

**Comment by rozmansi** [comment]
The problem can be much worse than only "two" credential prompts:
![image](https://user-images.githubusercontent.com/6889694/62870852-a06fed80-bd1a-11e9-9997-0ef433f103cc.png)

Working on a fix...

**Comment by ikreb7** [comment]
Thank you very much that you fix this bug!

I have one question. Do you build a new version that fix this problem, e.g. 1.2g?

**Comment by rozmansi** [comment]
I am working on one more bug, then making a release. Hopefully, early next week.

**Comment by ikreb7** [comment]
Hello Simon,

sorry that I probably annoy you. I saw that you had fix the problem, so I want to ask when you build the next version?

**Comment by rozmansi** [comment]
I apologize.

I was unable to reproduce that other bug I was after and I gave up on it... And totally forgot I promised a release. Stay tuned... Will build one today.

**Comment by ikreb7** [comment]
Perfect. Thank you.

**Comment by rozmansi** [comment]
Here you go: https://github.com/Amebis/GEANTLink/releases/tag/1.2g
