### ISSUE TITLE
uninstaller not found

### ISSUE THREAD

**Issue by AngelusGi** [Amebis/GEANTLink#29]
program manager in windows can't uninstall it

**Comment by rozmansi** [comment]
I will need more information to be able to help you uninstall it... Which version of GÉANTLink is this and which platform: 32 or 64-bit? (I need this to look up the exact product code.)

**Comment by AngelusGi** [comment]
platfrom: windows 10 pro x64 v.18362.356
GÉANTLink Event Monitor

**Comment by rozmansi** [comment]
If this is GÉANTLink 1.2g x64, run this on the command line:

```BAT
msiexec /x {9724DC5C-8574-47AF-9978-04ED7FA83EF4} /l* "%USERPROFILE%\Desktop\GEANTLink-uninstall.log"
```

This command will attempt to uninstall the GÉANTLink. `{9724DC5C-8574-47AF-9978-04ED7FA83EF4}` is the product GUID of the [GEANTLink-x64.msi v1.2g](https://github.com/Amebis/GEANTLink/releases/download/1.2g/GEANTLink-x64.msi).

Afterwards, locate the `GEANTLink-uninstall.log` file on your desktop and send it to me for analysis.
