### ISSUE TITLE
How do I set a connection?

### ISSUE THREAD

**Issue by pedroprieto** [Amebis/GEANTLink#30]
Hi,

I have installed the MSI package. How can I set the WiFi parameters? I would like to connect to a TTLS-PAP WiFi Network. I click on the SSID but I only get the regular Windows prompt. Is there any GUI?

Thanks!!

**Comment by rozmansi** [comment]
To edit existing WiFi connection, I use this (for example _eduroam_ WiFi connection):
```
WLANManager profile eduroam
```
This brings up Win32 WiFi connection dialog. There, you can change the EAP method to any method supported by GÉANTLink and click "Settings..." button to bring the GÉANTLink GUI. Then "+" button to add initial authority...

Note: WLANManager is a separate download. I am considering bundling it inside the MSI so it gets installed to `C:\Program Files\GEANTLink`, now that the official CAT installer no longer uses GÉANTLink. GÉANTLink used to be installed and provisioned by CAT installer, hence its GUI is not very exposed.

If the WiFi connection does not exist yet on your computer, I use this first:
```
netsh wlan add profile filename=eduroam-Arnes.xml user=all
```

**Comment by pedroprieto** [comment]
Ok. Thanks!!!
