### ISSUE TITLE
Windows 7 supplicant has no usable cipher suite. Does the GEANTLink help me?

### ISSUE THREAD

**Issue by bflmpsvz** [Amebis/GEANTLink#31]
I am trying to connect to eduroam with Windows 7. The problem is that cipher suite TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030) is needed. Does the GEANTLink offer any solution of this problem? I have installed v1.2c and instead of PEAP I am trying GEANTLink EAP-TTLS, but "ERROR_PPP_INVALID_PACKET returned...

**Comment by rozmansi** [comment]
GÉANTLink is using built-in Windows crypto: Schannel. On Windows 7, Schannel supports up to TLS 1.1 and SHA-1 (IIRC). Definitely not TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384.

Viable solution would be to rewrite the TLS in GÉANTLink to switch to OpenSSL, Mbed TLS or some other crypto library that is kept up-to-date.

Unfortunately, GÉANT sunset support for GÉANTLink, and I am not in position to maintain this project on our own. Would require financing to justify further development to our CEO.

**Comment by bflmpsvz** [comment]
At last I installed Cisco AnyConnect 4.10.06079 and it works! More exactly, I had to find the whole pack including NAM Network Access Manager, this is the part I need, and also I had to change the registry to solve the error code 0x8004a029 :
https://community.arubanetworks.com/browse/articles/blogviewer?blogkey=9300ed35-468f-4285-a5bf-a00a66ab7d04
