### ISSUE TITLE
Password dialog is shown too short

### ISSUE THREAD

**Issue by sko789** [Amebis/GEANTLink#33]
We have often the problem, that the password dialog from GEANTlink is only
shown for milliseconds. 
The dialog window appears and disappears in same second - no chance to enter username / password.
This happens very often when people are trying to enter a new password or in basic setup.
After several attempts (more than 5 to 10 times clicking on WLAN "connect" button) the 
dialog appears stable (mostly). Sometimes a computer reboot is needed to achieve this.

Is it possible to invoke that password dialog by hand? Or to enter the password somewhere else?

Environment: Windows 10 LTSC 2019 + 2021

**Comment by rozmansi** [comment]
Hi!

The credential dialog is dismissed as soon as GÉANTLink detects the authentication server is no longer listening to the EAP supplicant - before this feature, the credential dialog remained open, but when user finally entered username and password, the EAP process already expired and authentication was futile. Maybe your authentication server has a very short timeout when waiting for the credentials? Maybe GÉANTLink detection is broken? Anyway, you can research the situation using included EventMonitor utility.

Or...

You can enter the password elsewhere, as you suggested. Once the Wi-Fi profile is configured, user may run `WLANManager profile <MyWiFiSSIDName>` (installed in C:\Program Files\GEANTLink, [documentation](https://github.com/Amebis/GEANTLink/blob/master/WLANManager/README.md)) and configure GÉANTLink settings there - including credentials to be used automatically when connecting to this network. This allows unattended (no password prompt) connection, as GÉANTLink will already have username & password to use when authenticating.

Or...

You can set a "realm" (any unique ID) for your network profile and use command line utility CredWrite ([download](https://github.com/Amebis/GEANTLink/releases), [documentation](https://github.com/Amebis/GEANTLink/blob/master/CredWrite/README.md)). This is how CAT installer used to install user credentials on eduroam setup.

Good luck, as GÉANTLink is no longer actively maintained product.
